### ISSUE TITLE
Onboarding bug

### ISSUE THREAD

**Issue by ShivamBansal07** [ik04/KaizenKlass-V3#17]
Description: Onboard page breaks when searching more then 5 letters.

![image](https://github.com/user-attachments/assets/58709237-da39-4671-bdd0-1c017b45b2a5)

**Comment by ik04** [comment]
Sorry ma

**Comment by ik04** [comment]
I'll fix pa

**Comment by ShivamBansal07** [comment]
> Sorry ma

Just pointing out da

**Comment by ShivamBansal07** [comment]
> I'll fix pa

You doing gods work already da

**Comment by ik04** [comment]
![2024-08-12-17:09:35-screenshot](https://github.com/user-attachments/assets/ade95c5f-aef5-44c6-a02e-6f53b9a334aa)
fixed
